### ISSUE TITLE
how muti band  storaged in mrf compressed by lerc 

### ISSUE THREAD

**Issue by lzxue** [nasa-gibs/mrf#28]
I had genarate 4 bands mrf file;
i read every tile from .idx  ,but how get the all bands data every tile?

**Comment by lucianpls** [comment]
@lzxue 
I believe you are asking for a way to generate an MRF with LERC in INTERLEAVE=PIXEL mode, so one tile will contains the data for all bands.  As opposed to the existing INTERLEAVE=BAND mode, where a tile contains data from a single band.
That set of options is not supported by MRF.  LERC is a single band algorithm by definition, so a multi-band LERC is just a sequence of the individual bands compressed with LERC, the band pixels are not really interleaved.
From the MRF point of view, there is nothing to be gained by considering it pixel interleaved.  It would make reading a single band from a multi-band MRF slower, since all the bands would have to be read at the same time.
